config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => "homes#about"
  get 'search' => 'searches#search'
  resources :users, only: [:show,:edit,:update]
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end
  resources :books do
    resources :book_comments
    resource :favorites, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  validates :title, presence: true
  validates :body, presence: true,
                length: {maximum:200}


  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end


  def self.search(search, word)
    if search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "perfect_match"
      @book = Book.where("#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end


end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
  attachment :profile_image
  validates :name, presence: true, uniqueness: true, length: {minimum:2, maximum:20 }
  validates :introduction, length: {maximum:50}

  def follow(other_user)
    unless self == other_user
      self.relationships.create(followed_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(followed_id: other_user.id)
    relationship.destroy
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end


  def self.search(search,word)
    if search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "perfect_match"
    　@user = User.where("#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @books = Book.all
    @user = current_user
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save(book_params)
      flash[:success] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      render :index
    end
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
    @new_book = Book.new
    @user = @book.user
    @users = User.all
    @book_comment = BookComment.new
    @book_comments = @book.book_comments
  end

  def edit
    @book = Book.find(params[:id])
    if current_user.id != @book.user.id
      redirect_to books_path
    end
  end

  def update
    @user = current_user
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, :only => [:show]

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @book = Book.new
    @user=User.find(params[:id])
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
   end
 end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
    if current_user.id != @user.id
      redirect_to user_path(current_user)
    end
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(@user.id), :notice => "You have updated user successfully"
    else
      render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<h2 class="mt-3">New book</h2>
  <%= form_with model: book, local: true do |f| %>

    <div class="form-group">
      <label for="book_title">Title</label>
      <%= f.text_field :title, class:"form-control" %>
    </div>

    <div class="form-group">
      <label for="book_opinion">Opinion</label>
      <%= f.text_area :body, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.submit 'Create Book', class:"btn btn-success" %>
    </div>

  <% end %>

app/views/books/edit.html.erb
<main>
<p id="notice"></p>
  <div class="container">

    <div class="row">

      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

        <h1>Editing Book</h1>

          <div>
        		<% if @book.errors.any? %>
            <h3><%= @book.errors.count %> errors prohibited this obj from being saved:</h3>

            <ul>
            <% @book.errors.full_messages.each do |message| %>

              <li>
              <%= message %>
              </li>

            <% end %>
            </ul>

            <% end %>
          </div>

        <%= form_with model:@book, local:true do |f|%>

          <div class="form-group">
            <label for="book_title">Title</label>
            <%= f.text_field :title, class:"form-control" %>
          </div>

          <div class="form-group">
            <label for="book_opinion">Opinion</label>
            <%= f.text_area :body, class:"form-control" %>
          </div>

          <div class="form-group">
            <%= f.submit 'Update Book', class:"btn btn-success"%>
          </div>

        <%= link_to 'Show', book_path %> | <%= link_to 'Back', books_path %>
        <% end %>

      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <p id="notice"></p>

  <div class="container px-5 px-sm-0">

    <div>
      <% if @book.errors.any? %>
      <%= @book.errors.count %>errors prohibited this obj from being saved:
        <ul>
          <% @book.errors.full_messages.each do |message| %>

            <li>
              <%= message %>
            </li>

          <% end %>
        </ul>
      <% end %>
    </div>

    <div class="row">

      <div class="col-md-3">
        <%= render 'users/abc', user: current_user %>
        <%= render 'books/list', book: @book %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h2>Books</h2>

          <table class="table table-hover table-inverse">

            <thead>

              <tr>
                <th></th>
                <th>Title</th>
                <th>Opinion</th>
                <th colspan="3"></th>
              </tr>

            </thead>

            <tbody>
            <% @books.each do |book| %>

              <tr>

                <td>
                  <%= link_to user_path(book.user) do %>
                    <%= attachment_image_tag book.user, :profile_image, fallback: "no_image.jpg", size: "40x40"%>
                  <% end %>
                </td>

                <td>
                  <%= link_to book.title, book_path(book) %>
                </td>
                <td>
                  <%= book.body %>
                </td>
                <td id="favorite_buttons_<%= book.id %>" >
                  <%= render "favorites/favorites", book: book %>
                </td>
                <td>
                  <%= link_to "#{book.book_comments.count} コメント",book_path(book.id) %>
                </td>

              </tr>

            </tbody>
            <% end %>

          </table>
        </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
<% flash.each do |message_type, message| %>
<p id="notice"><%= message %></p>
<% end %>

    <div class="container px-5 px-sm-0">

      <div class="row">

         <div class="col-md-3">
            <%= render 'users/abc', user: @user %>
            <%= render 'books/list', book: @new_book %>
         </div>

         <div class="col-md-8 offset-md-1">
            <h2>Book detail</h2>

            <table class="table table-hover table-inverse">

               <tbody>
               <% if @book.user_id == current_user.id %>

                 <tr>

                    <td>
                        <%= link_to user_path(@user.id) do %>
                        <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "40x40"%>
                        <% end %>
                    <br>
                    <%= link_to @user.name, user_path(@user) %></td>
                    <td><%= link_to @book.title, book_path(@book) %></td>
                    <td><%= @book.body %></td>
                    <td>
                      <% if @book.favorited_by?(current_user) %>
                      <p>
                        <%= link_to book_favorites_path(@book), method: :delete do %>
                          ♥<%= @book.favorites.count %>
                        <% end %>
                      </p>
                      <% else %>
                      <p>
                        <%= link_to book_favorites_path(@book), method: :post do %>
                          ♡<%= @book.favorites.count %>
                        <% end %>
                      </p>
                    <% end %>
                    </td>
                    <td><%= link_to 'Edit', edit_book_path(@book), class:"btn btn-sm btn-success"%></td>
                    <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: {confirm: "本当に消しますか？"}, class:"btn btn-sm btn-danger" %></td>

                 </tr>
                 <% else %>

                 <tr>

                    <td>
                      <%= link_to user_path(@user.id) do %>
                      <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "40x40"%>
                      <% end %><br>
                      <%= link_to @user.name, user_path(@user) %>
                    </td>
                    <td>
                      <%= link_to @book.title, book_path(@book) %>
                    </td>
                    <td>
                      <%= @book.body %>
                    </td>
                    <td id="favorite_buttons_<%= @book.id %>" >
                      <%= render "favorites/favorites", book: @book %>
                    </td>
                    <td>
                      <p>コメント件数：<%= @book.book_comments.count %></p>
                    </td>

                 </tr>
                 <% end %>

               </tbody>

            </table>
            <div id="comments_area">
              <%= render 'book_comments/index', book_comments: @book.book_comments %>
            </div>
            <div class="new-comment">
              <%= render 'book_comments/form', book: @book ,book_comment: @book_comment %>
            </div>

         </div>

      </div>

     </div>

 </main>

app/views/rooms/show.html.erb
<h1>DM</h1>

<h4>参加者</h4>
<% @entries.each do |e| %>
  <h5><strong><a href="/users/<%= e.user.id %>"><%= e.user.name%>さん</a></strong></h5>
<% end %>

<hr>
<% if @messages.present? %>
  <% @messages.each do |m| %>
    <strong><%= m.content %></strong>
    <small>by <strong><a href="/users/<%= m.user_id %>"><%= m.user.name %>さん</a></strong></small>
    <hr>
  <% end %>
<% else %>
  <h3 class="text-center">メッセージはまだありません</h3>
<% end %>

<%= form_for @message do |f| %>
  <%= f.text_field :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
  <%= f.hidden_field :room_id, :value => @room.id %>
  <br>
  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "ユーザー一覧に戻る", users_path %>

app/views/users/_abc.html.erb
<h2>User info</h2>
  <%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "100x100"%>
      <table class="table">
          <tbody>
            <tr></tr>
            <tr>
          	  <th>name</th>
          	  <th><%= user.name %></th>
            </tr>
            <tr>
          	  <th>introduction</th>
          	  <th><%= user.introduction %></th>
            </tr>
            <tr>
              <th>follows</th>
              <th><%= link_to user.followings.count, user_followings_path(user) %></th>
            </tr>
            <tr>
              <th>followers</th>
              <th><%= link_to user.followers.count, user_followers_path(user) %></th>
            </tr>
          </tbody>
          </table>
    <div class="row">
    <% unless current_user == user %>
      <% if current_user.following?(user) %>
       <%= link_to "フォロー外す", user_relationships_path(user), method: :delete, class:"btn btn-info btn-sm btn-block mb-3" %>
      <% else %>
        <%= link_to "フォローする", user_relationships_path(user), method: :post, class:"btn btn-info btn-sm btn-block mb-3" %>
      <% end %>
    <% end %>
    <%= link_to edit_user_path(user), class: "btn btn-outline-secondary btn-block" do %>
    <span class="fas fa-user-cog"> </span>
    <% end %>
    </div>

app/views/users/edit.html.erb
<main>
      <div class="container">
          <div class="row">
            <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
            <h2>User info</h2>

              <div>
          		<% if @user.errors.any? %>
              <h3><%= @user.errors.count %> errors prohibited this obj from being saved:</h3>

                <ul>
                <% @user.errors.full_messages.each do |message| %>

                  <li>
                  <%= message %>
                  </li>

                <% end %>
                </ul>

              <% end %>
              </div>
            <%= form_with model:@user, local:true do |f| %>

              <div class="form-group">
                <label for="user_name">Name</label>
                <%= f.text_field :name, autofocus: true, class:"form-control" %>
              </div>
             <div class="form-group">
                <label for="user_image">Image</label>
                <%= f.attachment_field :profile_image, autofocus: true, class:"form-control-file user_image" %>
              </div>
              <div class="form-group">
                <label for="user_introduction">Introduction</label>
                <%= f.text_area :introduction, autofocus: true, class:"form-control" %>
              </div>
              <div class="form-group">
                <%= f.submit "Update User", class:"btn btn-secondary" %>
              </div>
              <% end %>
            </div>
          </div>

      </div>
  </main>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">


    <div class="row">

        <div class="col-md-3">

                <%= render 'users/abc', user: @user %>
                <%= render 'books/list', book: @book %>

        </div>

        <div class="col-md-8 offset-md-1">
            <h2>Users</h2>
                <table class="table table-hover table-inverse">

                    <thead>

                        <tr>
                            <th>Image</th>
                            <th>name</th>
                            <th colspan="3"></th>
                        </tr>

                    </thead>

                    <tbody>
                    <% @users.each do |user| %>

                        <tr>
                            <td><%= attachment_image_tag user, :profile_image, fallback: "no_image.jpg", size: "40x40"%></td>
                            <td><%= user.name%></td>
                            <td>フォロー数: <%= user.followings.count %></td>
                            <td>フォロワー数: <%= user.followers.count %></td>
                            <td>
                            <% unless current_user == user %>
                              <% if current_user.following?(user) %>
                               <%= link_to "フォロー外す", user_relationships_path(user), method: :delete %>
                              <% else %>
                                <%= link_to "フォローする", user_relationships_path(user), method: :post %>
                              <% end %>
                            <% end %>
                            </td>
                            <td><%= link_to 'Show', user_path(user)%></td>
                        </tr>

                    </tbody>
                    <% end %>
                </table>

        </div>
    </div>
</div>

app/views/users/show.html.erb
<main>
<div class="container px-5 px-sm-0">

    <div class="row">
        <div class="col-md-3">
                <%= render 'users/abc', user: @user %>
                <%= render 'books/list', book: @book %>
        </div>
        <div class="col-md-8 offset-md-1">
            <h2>Books</h2>
                <table class="table table-hover table-inverse">

                    <thead>

                        <tr>
                            <th></th>
                            <th>Title</th>
                            <th>Opinion</th>
                            <th colspan="3"></th>
                        </tr>

                    </thead>

                    <tbody>
                         <% @books.each do |book| %>
                        <tr>
                            <td>
                                <%= link_to user_path(@user.id) do %>
                                    <%= attachment_image_tag @user, :profile_image, fallback: "no_image.jpg", size: "40x40"%>
                                <% end %>
                            </td>
                            <td><%= link_to book.title, book_path(book) %></td>
                            <td><%= book.body %></td>
                            <td id="favorite_buttons_<%= book.id %>" >
                              <%= render "favorites/favorites", book: book %>
                            </td>
                            <td>
                              <p>コメント件数：<%= book.book_comments.count %></p>
                            </td>

                        </tr>

                    </tbody>
                    <% end %>
                </table>
                <div>
                    <% unless @user.id == current_user.id %>
                      <% if (current_user.following? @user) && (@user.following? current_user)  %>
                      <% if @isRoom == true %>
                        <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-primary btn-lg">チャットへ</a>
                      <% else %>
                        <%= form_for @room do |f| %>
                          <%= fields_for @entry do |e| %>
                            <%= e.hidden_field :user_id, value: @user.id %>
                          <% end %>
                          <%= f.submit "チャットを始める", class:"btn btn-primary btn-lg user-show-chat"%>
                        <% end %>
                      <% end %>
                      <% end %>
                    <% end %>
                </div>
        </div>
    </div>
</div>
</main>